package vista;

import java.awt.Dimension;
import javax.swing.JDesktopPane;

/**
 *
 * @author GL753VD
 */
public class FrmMenu extends javax.swing.JFrame {

    public static JDesktopPane JDektopPane_menu;
    
    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setSize(new Dimension (1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocale(null);
        this.setTitle("Sistema de Ventas");
        this.setLayout(null);
        JDektopPane_menu = new JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.JDektopPane_menu.setBounds(0, 0, ancho, alto - 110);
        this.add(JDektopPane_menu);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Usuario = new javax.swing.JMenu();
        Nuevo_Usuario = new javax.swing.JMenuItem();
        Gestionar_Usuario = new javax.swing.JMenuItem();
        Producto = new javax.swing.JMenu();
        Nuevo_Producto = new javax.swing.JMenuItem();
        Gestionar_Productos = new javax.swing.JMenuItem();
        Actualizar_Stock = new javax.swing.JMenuItem();
        Proveedor = new javax.swing.JMenu();
        Nuevo_Proveedor = new javax.swing.JMenuItem();
        Gestionar_Proveedores = new javax.swing.JMenuItem();
        Cliente = new javax.swing.JMenu();
        Nuevo_Cliente = new javax.swing.JMenuItem();
        Gestionar_Cliente = new javax.swing.JMenuItem();
        Venta = new javax.swing.JMenu();
        Nueva_Venta = new javax.swing.JMenuItem();
        Gestionar_Ventas = new javax.swing.JMenuItem();
        Cerrar_Sesion = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario.setText("Usuario");
        Usuario.setPreferredSize(new java.awt.Dimension(200, 50));

        Nuevo_Usuario.setText("Nuevo Usuario");
        Usuario.add(Nuevo_Usuario);

        Gestionar_Usuario.setText("Gestionar Usuario");
        Usuario.add(Gestionar_Usuario);

        jMenuBar1.add(Usuario);

        Producto.setText("Producto");
        Producto.setPreferredSize(new java.awt.Dimension(200, 50));

        Nuevo_Producto.setText("Nuevo Producto");
        Nuevo_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nuevo_ProductoActionPerformed(evt);
            }
        });
        Producto.add(Nuevo_Producto);

        Gestionar_Productos.setText("Gestionar Productos");
        Gestionar_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gestionar_ProductosActionPerformed(evt);
            }
        });
        Producto.add(Gestionar_Productos);

        Actualizar_Stock.setText("Actualizar Stock");
        Actualizar_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar_StockActionPerformed(evt);
            }
        });
        Producto.add(Actualizar_Stock);

        jMenuBar1.add(Producto);

        Proveedor.setText("Proveedor");
        Proveedor.setPreferredSize(new java.awt.Dimension(200, 50));

        Nuevo_Proveedor.setText("Nuevo Proveedor");
        Nuevo_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nuevo_ProveedorActionPerformed(evt);
            }
        });
        Proveedor.add(Nuevo_Proveedor);

        Gestionar_Proveedores.setText("Gestionar Proveedores");
        Gestionar_Proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gestionar_ProveedoresActionPerformed(evt);
            }
        });
        Proveedor.add(Gestionar_Proveedores);

        jMenuBar1.add(Proveedor);

        Cliente.setText("Cliente");
        Cliente.setPreferredSize(new java.awt.Dimension(200, 50));

        Nuevo_Cliente.setText("Nuevo Cliente");
        Nuevo_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nuevo_ClienteActionPerformed(evt);
            }
        });
        Cliente.add(Nuevo_Cliente);

        Gestionar_Cliente.setText("Gestionar Cliente");
        Gestionar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gestionar_ClienteActionPerformed(evt);
            }
        });
        Cliente.add(Gestionar_Cliente);

        jMenuBar1.add(Cliente);

        Venta.setText("Venta");
        Venta.setPreferredSize(new java.awt.Dimension(200, 50));

        Nueva_Venta.setText("Nueva Venta");
        Nueva_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nueva_VentaActionPerformed(evt);
            }
        });
        Venta.add(Nueva_Venta);

        Gestionar_Ventas.setText("Gestionar Ventas");
        Venta.add(Gestionar_Ventas);

        jMenuBar1.add(Venta);

        Cerrar_Sesion.setText("Cerrar Sesion");
        Cerrar_Sesion.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem15.setText("Cerrar Sesion");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        Cerrar_Sesion.add(jMenuItem15);

        jMenuBar1.add(Cerrar_Sesion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Gestionar_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gestionar_ProductosActionPerformed
        // TODO add your handling code here:
     InterGestionProductos interGestionProductos = new InterGestionProductos();
        JDektopPane_menu.add(interGestionProductos);
        interGestionProductos.setVisible(true);
        
    }//GEN-LAST:event_Gestionar_ProductosActionPerformed

    private void Gestionar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gestionar_ClienteActionPerformed
        // TODO add your handling code here:
        InterGestionClientes interGestionClientes = new InterGestionClientes();
        JDektopPane_menu.add(interGestionClientes);
        interGestionClientes.setVisible(true);
    }//GEN-LAST:event_Gestionar_ClienteActionPerformed

    private void Nuevo_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nuevo_ClienteActionPerformed
        // TODO add your handling code here:
        InterCliente interCliente = new InterCliente();
        JDektopPane_menu.add(interCliente);
        interCliente.setVisible(true);
        
    }//GEN-LAST:event_Nuevo_ClienteActionPerformed

    private void Nuevo_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nuevo_ProductoActionPerformed
        // TODO add your handling code here:
        InterProducto interProducto = new InterProducto();
        JDektopPane_menu.add(interProducto);
        interProducto.setVisible(true);
        
    }//GEN-LAST:event_Nuevo_ProductoActionPerformed

    private void Nuevo_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nuevo_ProveedorActionPerformed
        // TODO add your handling code here:
           InterProveedor interProveedor = new InterProveedor();
           JDektopPane_menu.add(interProveedor);
           interProveedor.setVisible(true);
    }//GEN-LAST:event_Nuevo_ProveedorActionPerformed

    private void Gestionar_ProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gestionar_ProveedoresActionPerformed
        // TODO add your handling code here:
          InterGestionProveedor interGestionProveedores = new InterGestionProveedor();
        JDektopPane_menu.add(interGestionProveedores);
        interGestionProveedores.setVisible(true);
    }//GEN-LAST:event_Gestionar_ProveedoresActionPerformed

    private void Actualizar_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar_StockActionPerformed
        // TODO add your handling code here:
         InterActualizarStock interActualizarStock = new InterActualizarStock();
         JDektopPane_menu.add(interActualizarStock);
         interActualizarStock.setVisible(true);
                                                  
                                               
        
    }//GEN-LAST:event_Actualizar_StockActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void Nueva_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nueva_VentaActionPerformed
        // TODO add your handling code here:
        InterVenta interVenta = new InterVenta();
         JDektopPane_menu.add(interVenta);
         interVenta.setVisible(true);
        
    }//GEN-LAST:event_Nueva_VentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Actualizar_Stock;
    private javax.swing.JMenu Cerrar_Sesion;
    private javax.swing.JMenu Cliente;
    private javax.swing.JMenuItem Gestionar_Cliente;
    private javax.swing.JMenuItem Gestionar_Productos;
    private javax.swing.JMenuItem Gestionar_Proveedores;
    private javax.swing.JMenuItem Gestionar_Usuario;
    private javax.swing.JMenuItem Gestionar_Ventas;
    private javax.swing.JMenuItem Nueva_Venta;
    private javax.swing.JMenuItem Nuevo_Cliente;
    private javax.swing.JMenuItem Nuevo_Producto;
    private javax.swing.JMenuItem Nuevo_Proveedor;
    private javax.swing.JMenuItem Nuevo_Usuario;
    private javax.swing.JMenu Producto;
    private javax.swing.JMenu Proveedor;
    private javax.swing.JMenu Usuario;
    private javax.swing.JMenu Venta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem15;
    // End of variables declaration//GEN-END:variables
}
