package vista;

import com.mysql.jdbc.Statement;
import conexion.Conexion;
import controlador.Ctrl_Proveedor;
import java.sql.Connection;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JTable;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import modelo.Proveedor;




/**
 *
 * @author GL753VD
 */
public class InterGestionProveedor extends javax.swing.JInternalFrame {

        private int idProveedor;
    
    public InterGestionProveedor() {
        initComponents();
        this.setSize(new Dimension (700, 400));
        this.setTitle("Administrar Proveedores");
        //Insertar tabla
        this.CargarTablaProveedores();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Administrar_Clientes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        AProveedores = new javax.swing.JScrollPane();
        TablaProveedores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Actualizar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Empresa = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        Text_Empresa = new javax.swing.JTextField();
        Text_Email = new javax.swing.JTextField();
        Text_Telefono = new javax.swing.JTextField();
        Fondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Administrar_Clientes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Administrar_Clientes.setForeground(new java.awt.Color(255, 255, 255));
        Administrar_Clientes.setText("Administrar Proveedores");
        getContentPane().add(Administrar_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        AProveedores.setViewportView(TablaProveedores);

        jPanel1.add(AProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 510, 190));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Actualizar.setBackground(new java.awt.Color(102, 255, 102));
        Actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        Eliminar.setBackground(new java.awt.Color(255, 51, 51));
        Eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel2.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 120, 80));

        Empresa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Empresa.setForeground(new java.awt.Color(255, 255, 255));
        Empresa.setText("Empresa");
        getContentPane().add(Empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        Email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        Telefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Telefono.setForeground(new java.awt.Color(255, 255, 255));
        Telefono.setText("Telefono");
        getContentPane().add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        Text_Empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_EmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(Text_Empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 272, 190, 30));

        Text_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Text_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 230, 30));
        getContentPane().add(Text_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 272, 190, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PIXELS.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
        
        if (Text_Empresa.getText().isEmpty() && Text_Email.getText().isEmpty()&& Text_Telefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completa los campos");
        } else {

            Proveedor proveedor = new Proveedor();
            Ctrl_Proveedor controlProveedor = new Ctrl_Proveedor();

            proveedor.setEmpresa(Text_Empresa.getText().trim());
            proveedor.setEmail(Text_Email.getText().trim());
            proveedor.setTelefono(Text_Telefono.getText().trim());
            

            if (controlProveedor.actualizar(proveedor, idProveedor)) {
                JOptionPane.showMessageDialog(null, "Datos del Proveedor actualizado");
                this.CargarTablaProveedores();
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar");
            }

        }
        
        
    }//GEN-LAST:event_ActualizarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
         Ctrl_Proveedor controlProveedor = new Ctrl_Proveedor();
        if (idProveedor == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un proveedor");
        } else {
            if (!controlProveedor.eliminar(idProveedor)) {
                JOptionPane.showMessageDialog(null, "Proveedor Eliminado");
                this.CargarTablaProveedores();
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar proveedor");
                this.Limpiar();
            }
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void Text_EmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_EmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_EmpresaActionPerformed

    private void Text_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_EmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JScrollPane AProveedores;
    private javax.swing.JButton Actualizar;
    private javax.swing.JLabel Administrar_Clientes;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Empresa;
    private javax.swing.JLabel Fondo;
    public static javax.swing.JTable TablaProveedores;
    private javax.swing.JLabel Telefono;
    private javax.swing.JTextField Text_Email;
    private javax.swing.JTextField Text_Empresa;
    private javax.swing.JTextField Text_Telefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
  //Metodo para limpiar
    private void Limpiar() {
        Text_Empresa.setText("");
        Text_Email.setText("");
        Text_Telefono.setText("");
        
    }



//Para mostrar todos los Proveedores Agregados
 
   private void CargarTablaProveedores(){
       Connection con = Conexion.conectar();
       DefaultTableModel model = new DefaultTableModel();
       String sql = "select * from Proveedor";
       Statement st;
       
       try {
           st = (Statement) con.createStatement();
           ResultSet rs = st.executeQuery(sql);
           InterGestionProveedor.TablaProveedores = new JTable(model);
           InterGestionProveedor.AProveedores.setViewportView(InterGestionProveedor.TablaProveedores);
           
           model.addColumn("idProveedor");
           model.addColumn("empresa");
           model.addColumn("email");
           model.addColumn("telefono");
           
           while(rs.next()){
                Object fila[] = new Object [4];
                
                for(int i =0; i <4; i++){
                   fila[i] = rs.getObject(i + 1); 
                }
                model.addRow(fila);
           
           }
           con.close();
           
       } catch (SQLException e) {
           System.out.println("Error al llenar la tabla Proveedor" + e);
           
       }
      //evento para obtener campo al cual el usuario da click
        //y obtener la interfaz que mostrara la informacion general
        TablaProveedores.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = TablaProveedores.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idProveedor = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosProveedoresSeleccionado(idProveedor);//metodo
                }
            }
        });
    
    
    }
   
   
    /*
     * **************************************************
     * Metodo que envia datos seleccionados
     * **************************************************
     */
    private void EnviarDatosProveedoresSeleccionado(int idProveedor) {
        try {
            Connection con = Conexion.conectar();
            PreparedStatement pst = con.prepareStatement(
                    "select * from Proveedor where idProveedor = '" + idProveedor + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                Text_Empresa.setText(rs.getString("empresa"));
                Text_Email.setText(rs.getString("email"));
                Text_Telefono.setText(rs.getString("telefono"));
                
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al seleccionar Proveedor: " + e);
        }
    }
       
}
